#テスト環境用

FROM node:20-alpine

# 作業ディレクトリ
WORKDIR /app

# package.json と lock ファイルを先にコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# 残りのファイルをコピー
COPY . .

# 開発サーバー起動
EXPOSE 3000

CMD ["npm", "run", "dev"]
